import { Metadata } from "next";
import NavigationBar from "./_components/navbar";
import { QueryProvider } from "@/providers/tanstack-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full">
      <NavigationBar />
      <QueryProvider>{children}</QueryProvider>
    </div>
  );
}
